CONFIG_NAME: 'stageII'

DATASET_NAME: 'birds_small'
EMBEDDING_TYPE: 'cnn-rnn'
Z_DIM: 100

TRAIN:
    FLAG: True
    PRETRAINED_MODEL: ''
    PRETRAINED_EPOCH: 600
    BATCH_SIZE: 32
    NUM_COPY: 4
    MAX_EPOCH: 1200
    SNAPSHOT_INTERVAL: 2
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    LR_DECAY_EPOCH: 100
    NUM_EMBEDDING: 4
    COEFF:
      KL: 2.0

GAN:
    EMBEDDING_DIM: 11
    DF_DIM: 7
    GF_DIM: 9
