CONFIG_NAME: 'stageI'

DATASET_NAME: 'birds_small'
EMBEDDING_TYPE: 'cnn-rnn'
Z_DIM: 100

TRAIN:
    FLAG: True
    PRETRAINED_MODEL: ''
    BATCH_SIZE: 64
    NUM_COPY: 4
    MAX_EPOCH: 1
    SNAPSHOT_INTERVAL: 1
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    LR_DECAY_EPOCH: 50
    NUM_EMBEDDING: 4
    COEFF:
      KL: 2.0

GAN:
    EMBEDDING_DIM: 11
    DF_DIM: 7
    GF_DIM: 9
