CONFIG_NAME: 'stageII'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
Z_DIM: 100

TRAIN:
    FLAG: True
    PRETRAINED_MODEL: '../ckt_logs/birds/stageII_2017_07_20_10_58_24/model.ckpt'
    BATCH_SIZE: 16
    NUM_COPY: 4
    MAX_EPOCH: 200
    SNAPSHOT_INTERVAL: 2000
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    LR_DECAY_EPOCH: 100
    NUM_EMBEDDING: 4
    COEFF:
      KL: 2.0

GAN:
    EMBEDDING_DIM: 128
    DF_DIM: 64
    GF_DIM: 128
